#Import needed package

In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

#Load Dataset

In [6]:
data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/LAB_AI SEM 5/PERTEMUAN 10-LSTM/IMDB Dataset.csv")

In [7]:
data.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [8]:
data.shape

(50000, 2)

In [9]:
type(data)

pandas.core.frame.DataFrame

In [11]:
data["sentiment"].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

#One Hot Encoding
#Label Encoder

In [12]:
data.replace({"sentiment" : {"positive" : 1, "negative" : 0}}, inplace=True)

In [13]:
data.head()

                                              review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1

#Data preprocessing

In [14]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [15]:
train_data, test_data = train_test_split(data, test_size=0.2, random_state=42)

In [16]:
train_data.shape

(40000, 2)

In [17]:
test_data.shape

(10000, 2)

In [19]:
tokenizer = Tokenizer(num_words = 5000)
tokenizer.fit_on_texts(test_data["review"])

In [22]:
X_train = pad_sequences(tokenizer.texts_to_sequences(train_data['review']), maxlen=200)
X_test = pad_sequences(tokenizer.texts_to_sequences(test_data['review']), maxlen=200)

In [21]:
X_train

[[192,
  49,
  10,
  787,
  2338,
  548,
  300,
  1,
  106,
  1724,
  2160,
  2,
  831,
  12,
  1,
  229,
  1,
  86,
  785,
  52,
  50,
  21,
  103,
  4,
  1,
  28,
  2056,
  101,
  35,
  25,
  34,
  116,
  1114,
  12,
  9,
  6,
  2378,
  1176,
  5,
  476,
  49,
  558,
  5,
  91,
  33,
  23,
  40,
  977,
  432,
  16,
  1,
  160,
  5,
  2841,
  24,
  20,
  3,
  3127,
  12,
  45,
  77,
  222,
  71,
  126,
  8,
  74,
  3385,
  190,
  20,
  237,
  2,
  1,
  426,
  7,
  7,
  10,
  210,
  146,
  22,
  62,
  28,
  16,
  79,
  376,
  300,
  3,
  19,
  18,
  9,
  210,
  27,
  297,
  12,
  14,
  1,
  119,
  460,
  2,
  14,
  1,
  1389,
  676,
  68,
  407,
  386,
  10,
  89,
  117,
  49,
  111,
  351,
  33,
  37,
  18,
  43,
  10,
  13,
  91,
  472,
  16,
  3,
  364,
  1011,
  61,
  8,
  1,
  461,
  199,
  1038,
  5,
  4636,
  8,
  3,
  179,
  4,
  34,
  405,
  782,
  683,
  12,
  3861,
  241,
  110,
  850,
  37,
  174,
  30,
  230,
  192,
  1,
  444,
  368,
  56,
  3057,
  3,
  276,
  7,
  7,
  152,
  1788,
  197,
  6,
  1,
  776,
  2301,
  1,
  1117,
  4,
  3423,
  3751,
  2097,
  2,
  143,
  146,
  3,
  212,
  4,
  3,
  203,
  340,
  2,
  146,
  1034,
  15,
  88,
  4,
  129,
  2795,
  18,
  10,
  157,
  98,
  4,
  1,
  3481,
  300,
  11,
  17,
  952,
  37,
  1,
  498,
  489,
  2506,
  255,
  73,
  75,
  106,
  106,
  687,
  60,
  84,
  1099,
  1300,
  5,
  238,
  129,
  23,
  3668,
  31,
  138,
  224,
  1066,
  14,
  4601,
  31,
  3,
  2476,
  2,
  8,
  11,
  6,
  3,
  468,
  14,
  606,
  4,
  1,
  747,
  3512,
  1,
  1103,
  2,
  73,
  3569,
  1,
  160,
  1526,
  1,
  1197,
  5,
  1870,
  1,
  951,
  1221,
  5,
  1,
  310,
  144,
  2842,
  2,
  412,
  591,
  7,
  7,
  1,
  282,
  6,
  4291,
  1076,
  5,
  27,
  40,
  14,
  1366,
  209,
  64,
  2,
  46,
  6,
  30,
  230,
  28,
  188,
  1422,
  8,
  1023,
  18,
  10,
  3935,
  78,
  1,
  228,
  66,
  358,
  70,
  54,
  28,
  5,
  4381,
  16,
  44,
  22,
  195,
  5,
  3,
  859,
  3223,
  1897,
  21,
  25,
  5,
  161,
  202,
  178,
  3,
  115,
  12,
  1318,
  466,
  77,
  222,
  5,
  332,
  2,
  3513,
  35,
  23,
  51,
  72,
  1913,
  14,
  9,
  1335,
  11,
  19,
  6,
  3,
  3758,
  2207,
  15,
  61,
  1,
  2294,
  461,
  551,
  2,
  3,
  170,
  2918,
  3053,
  1809,
  5,
  597,
  9,
  37,
  1,
  4451,
  463,
  162,
  210,
  374,
  4301],
 [10,
  118,
  22,
  104,
  1,
  440,
  17,
  10,
  100,
  22,
  104,
  1,
  440,
  17,
  10,
  2511,
  1,
  273,
  97,
  150,
  16,
  302,
  32,
  522,
  2,
  10,
  1520,
  255,
  533,
  4,
  150,
  570,
  9,
  550,
  570,
  154,
  657,
  1,
  3815,
  42,
  4,
  1,
  445,
  7,
  7,
  10,
  36,
  4438,
  99,
  190,
  1495,
  2,
  600,
  18,
  67,
  61,
  27,
  2001,
  14,
  3,
  1495,
  616,
  30,
  3,
  4438,
  182,
  7,
  7,
  1,
  468,
  6,
  324,
  513,
  96,
  256,
  5,
  75,
  1,
  310,
  5,
  413,
  1,
  115,
  193,
  5,
  27,
  32,
  1380,
  16,
  734,
  1487,
  37,
  28,
  134,
  5,
  152,
  319,
  6,
  327,
  2,
  1526,
  3575,
  38,
  29,
  24,
  714,
  216,
  612,
  14,
  2270,
  1487,
  6,
  680,
  245,
  72,
  657,
  3,
  199,
  9,
  21,
  200,
  42,
  4,
  1,
  65,
  244,
  134,
  6,
  1312,
  754,
  1,
  12,
  76,
  3635,
  20,
  1,
  267,
  6,
  648,
  14,
  520,
  14,
  244,
  134,
  6,
  1625,
  8,
  1163,
  138,
  14,
  422,
  1,
  3106,
  31,
  1,
  417,
  107,
  23,
  149,
  78,
  21,
  67,
  15,
  1,
  101,
  4128,
  2,
  2504,
  1429,
  2,
  1,
  842,
  1,
  107,
  656,
  52,
  8,
  6,
  22,
  189,
  427,
  1,
  518,
  12,
  26,
  6,
  4233,
  52,
  8,
  3,
  1722,
  616,
  5,
  2583,
  3,
  413,
  37,
  1,
  310,
  7,
  7,
  43,
  1487,
  66,
  22,
  248,
  138,
  32,
  1387,
  107,
  35,
  110,
  62,
  15,
  1,
  74,
  101,
  8,
  1,
  17,
  2,
  647,
  4475,
  6,
  1061,
  557,
  16,
  262,
  5,
  2583,
  934,
  2,
  1,
  182,
  135,
  1147,
  34,
  754,
  2,
  29,
  1,
  615,
  477,
  233,
  96,
  1034,
  11,
  17,
  100,
  25,
  77,
  1669,
  18,
  9,
  207,
  89,
  104,
  9],
 [3,
  1474,
  108,
  65,
  2992,
  4,
  1,
  1103,
  16,
  3665,
  3120,
  20,
  1707,
  4273,
  2,
  84,
  11,
  6,
  328,
  31,
  4022,
  81,
  5,
  1560,
  5,
  244,
  74,
  1,
  65,
  2585,
  20,
  3,
  35,
  487,
  34,
  71,
  5,
  27,
  3,
  2022,
  1678,
  14,
  69,
  14,
  3,
  48,
  690,
  2,
  375,
  3,
  1533,
  6,
  53,
  3402,
  5,
  85,
  14,
  1,
  65,
  3983,
  73,
  63,
  1,
  1371,
  1912,
  1,
  2242,
  8,
  24,
  876,
  305,
  1361,
  2,
  84,
  26,
  15,
  1,
  1499,
  12,
  381,
  85,
  3,
  304,
  2,
  734,
  65],
 [11,
  1549,
  249,
  3206,
  6,
  3,
  485,
  3993,
  1978,
  15,
  32,
  35,
  1128,
  400,
  5,
  891,
  122,
  24,
  123,
  4278,
  31,
  47,
  4,
  1,
  21,
  76,
  123,
  4332,
  124,
  536,
  20,
  2,
  35,
  40,
  634,
  5,
  27,
  3875,
  1,
  3206,
  228,
  86,
  5,
  3,
  170,
  1880,
  837,
  60,
  61,
  945,
  8,
  47,
  2169,
  926,
  1204,
  3,
  4016,
  60,
  488,
  807,
  280,
  32,
  1172,
  2039,
  1310,
  35,
  488,
  550,
  1309,
  526,
  22,
  5,
  718,
  3,
  796,
  743,
  42,
  4,
  1,
  1533,
  4,
  263,
  8,
  11,
  445,
  1,
  105,
  2590,
  1825,
  3663,
  1689,
  4048,
  8,
  1,
  133,
  10,
  173,
  131,
  146,
  739,
  12,
  11,
  19,
  289,
  54,
  2043,
  4,
  1,
  4,
  4865,
  16,
  1,
  60,
  9,
  3721,
  8,
  455,
  748,
  2,
  12,
  9,
  6,
  1506,
  5,
  1500,
  2777,
  52,
  1,
  2092,
  18,
  606,
  96,
  1109,
  313,
  4,
  2,
  38,
  1475,
  15,
  60,
  3366,
  3206,
  66,
  31,
  92,
  404,
  327,
  4255],
 [87,
  4,
  29,
  10,
  261,
  12,
  99,
  23,
  362,
  126,
  37,
  1,
  2104,
  951,
  102,
  4,
  1,
  1920,
  2,
  1353,
  99,
  37,
  11,
  277,
  161,
  702,
  5,
  2478,
  3,
  212,
  4,
  1168,
  761,
  810,
  1163,
  68,
  93,
  99,
  68,
  161,
  1881,
  5,
  75,
  418,
  2,
  149,
  14,
  2919,
  5,
  201,
  453,
  2547,
  2,
  379,
  7,
  7,
  300,
  1,
  2996,
  2,
  455,
  62,
  80,
  99,
  68,
  93,
  31,
  3,
  4,
  1077,
  17,
  97,
  17,
  68,
  31,
  1390,
  2,
  248,
  4286,
  4,
  290,
  9,
  880,
  1,
  7,
  7,
  92,
  388,
  2244,
  7,
  7,
  1315,
  1004,
  44,
  40,
  324,
  22,
  149,
  22,
  288,
  22,
  123,
  18,
  1,
  147,
  6,
  73,
  103,
  90,
  149,
  78,
  1099,
  328,
  5,
  99,
  5,
  27,
  149,
  250,
  15,
  3,
  179,
  36,
  11,
  15,
  3,
  170,
  62,
  149,
  18,
  33,
  1022,
  131,
  902,
  83,
  232,
  149,
  1,
  462,
  109,
  70,
  1,
  462,
  6,
  9,
  1,
  2250,
  248,
  31,
  6,
  9,
  1,
  4598,
  485,
  4006,
  2030,
  2357,
  3365,
  6,
  9,
  1,
  31,
  1,
  17,
  6,
  40,
  22,
  149,
  7,
  7,
  18,
  1674,
  22,
  57,
  296,
  41,
  2244,
  12,
  6,
  1,
  2,
  9,
  6,
  130,
  10,
  1261,
  12,
  1163,
  25,
  216,
  5,
  3,
  231,
  10,
  25,
  113,
  11,
  8,
  106,
  74,
  99,
  14,
  69,
  29,
  1,
  56,
  21,
  40,
  117,
  90,
  172,
  5,
  133,
  69,
  29,
  101,
  23,
  573,
  14,
  33,
  23,
  1432,
  8,
  1,
  360,
  4,
  1,
  17,
  2,
  1366,
  209,
  573,
  49,
  33,
  1740,
  8,
  1,
  133,
  221,
  407,
  54,
  654,
  16,
  2578,
  30,
  29,
  7,
  7,
  29,
  8,
  29,
  10,
  67,
  131,
  12,
  10,
  1709,
  15,
  3,
  79,
  518,
  97,
  315,
  11,
  17,
  9,
  13,
  1,
  28,
  17,
  12,
  93,
  70,
  963,
  12,
  73,
  241,
  367,
  47,
  164,
  535,
  8,
  17,
  243,
  174,
  7,
  7,
  705,
  317,
  1169],
 [10,
  89,
  117,
  84,
  11,
  17,
  2278,
  34,
  106,
  1233,
  896,
  20,
  11,
  2085,
  146,
  3,
  188,
  340,
  2,
  234,
  53,
  1034,
  15,
  1,
  65,
  11,
  4396,
  224,
  19,
  693,
  2312,
  18,
  55,
  43,
  10,
  293,
  1,
  334,
  111,
  53,
  334,
  1041,
  2117,
  14,
  1,
  516,
  2,
  29,
  186,
  2332,
  4824,
  1,
  327,
  3876,
  2,
  1569,
  1397,
  517,
  4683,
  11,
  1207,
  1669,
  294,
  3998,
  42,
  84,
  1017,
  12,
  336,
  13,
  43,
  21,
  330,
  12,
  2,
  197,
  12,
  13,
  1062,
  600,
  3596,
  1142,
  9,
  241,
  13,
  1,
  88,
  4540,
  149,
  171,
  4,
  1,
  17,
  274,
  492,
  36,
  11,
  17,
  18,
  43,
  326,
  3,
  340,
  38,
  22,
  327,
  1889,
  89,
  63,
  9,
  587],
 [2370,
  3128,
  431,
  3,
  179,
  4,
  668,
  148,
  15,
  55,
  321,
  4,
  32,
  295,
  4,
  49,
  6,
  172,
  20,
  72,
  1,
  160,
  66,
  43,
  21,
  67,
  761,
  12,
  46,
  6,
  54,
  115,
  38,
  65,
  1,
  335,
  313,
  23,
  3,
  993,
  2,
  55,
  1,
  475,
  6,
  386,
  11,
  19,
  13,
  532,
  31,
  1993,
  9,
  13,
  1,
  61,
  19,
  12,
  26,
  123,
  532,
  2,
  1,
  281,
  6,
  648],
 [1415,
  4433,
  7,
  7,
  62,
  3,
  48,
  214,
  18,
  97,
  32,
  3096,
  15,
  47,
  930,
  8,
  3,
  4954,
  2,
  47,
  4,
  4052,
  220,
  1608,
  5,
  2902,
  38,
  245,
  47,
  442,
  4,
  151,
  1238,
  26,
  3022,
  18,
  97,
  3,
  346,
  136,
  220,
  1067,
  288,
  174,
  11,
  56,
  656,
  52,
  8,
  3,
  560,
  109,
  8,
  60,
  220,
  443,
  5,
  498,
  16,
  3,
  136,
  37,
  3,
  741,
  4,
  1094,
  429,
  15,
  276,
  1259,
  2,
  816,
  709,
  18,
  73,
  29,
  117,
  2,
  73,
  29,
  117,
  12,
  220,
  72,
  55,
  1,
  4,
  1094,
  429,
  7,
  7,
  10,
  62,
  469,
  5,
  36,
  11,
  17,
  112,
  32,
  340,
  2,
  29,
  189,
  1,
  627,
  127,
  1434,
  96,
  106,
  1679,
  12,
  62,
  1,
  624,
  42,
  4,
  70,
  922,
  1194,
  1,
  4,
  544,
  935,
  1,
  4954,
  120,
  1,
  2192,
  310,
  6,
  1203,
  3,
  346,
  2561,
  4,
  1,
  3096,
  598,
  15,
  494,
  162,
  276,
  353,
  2148,
  11,
  818,
  12,
  1,
  1407,
  4954,
  8,
  60,
  13,
  15,
  219,
  162,
  4744,
  1319,
  1,
  983,
  1091,
  28,
  4,
  60,
  935,
  1,
  745,
  4,
  28,
  4,
  1,
  983,
  1091,
  3685,
  7,
  7,
  46,
  23,
  74,
  1679,
  86,
  2,
  1,
  115,
  60,
  8,
  2713,
  193,
  5,
  27,
  53,
  218,
  2,
  4082,
  491,
  16,
  3,
  136,
  92,
  9,
  442,
  4,
  1961,
  3,
  3514,
  4,
  2,
  8,
  60,
  9,
  7,
  7,
  1,
  111,
  173,
  62,
  27,
  297,
  5,
  27,
  232,
  126,
  72,
  1569,
  2051,
  15,
  8,
  1,
  917,
  199,
  399,
  32,
  845,
  239,
  1,
  384,
  4,
  1,
  179,
  75,
  31,
  215,
  112,
  250,
  48,
  38,
  79,
  7,
  7,
  1,
  335,
  313,
  23,
  626,
  215,
  112,
  1306,
  7,
  7,
  705,
  338,
  162],
 [1,
  81,
  35,
  23,
  79,
  11,
  19,
  23,
  141,
  35,
  89,
  377,
  19,
  5,
  883,
  15,
  129,
  23,
  1,
  81,
  35,
  108,
  17,
  2,
  5,
  98,
  17,
  12,
  153,
  314,
  6,
  3,
  2953,
  116,
  19,
  12,
  205,
  301,
  2417,
  2,
  274,
  55,
  344,
  30,
  87,
  18,
  49,
  9,
  1526,
  8,
  115,
  9,
  51,
  72,
  166,
  52,
  16,
  8,
  2461,
  7,
  7,
  28,
  147,
  8,
  940,
  41,
  1,
  17,
  12,
  1479,
  70,
  13,
  44,
  345,
  4,
  203,
  60,
  283,
  3,
  1031,
  171,
  141,
  1442,
  4,
  19,
  203,
  76,
  1593,
  84,
  646,
  203,
  6,
  8,
  1,
  17,
  190,
  8,
  2,
  114,
  2,
  8,
  1,
  1018,
  796,
  796,
  2,
  796,
  23,
  29,
  608,
  8,
  1,
  635,
  671,
  2,
  9,
  6,
  149,
  84,
  47,
  4,
  1,
  3275,
  271,
  42,
  16,
  1739,
  8,
  1,
  134,
  120,
  1,
  343,
  23,
  1309,
  4196,
  4,
  6,
  15,
  50,
  1,
  343,
  1977,
  137,
  36,
  59,
  6,
  57,
  251,
  2,
  92,
  59,
  272,
  121,
  5,
  3429,
  5,
  202,
  85,
  137,
  50,
  1,
  343,
  1977,
  1,
  59,
  76,
  27,
  57,
  251,
  4153,
  737,
  1,
  995,
  183,
  1,
  105,
  1288,
  46,
  23,
  29,
  2714,
  4,
  116,
  36,
  11,
  935,
  1,
  17,
  2,
  136,
  9,
  205,
  165,
  36,
  3,
  4766,
  20,
  1,
  1054,
  1,
  145,
  1533,
  4,
  19,
  76,
  1593,
  84,
  48,
  11,
  17,
  62,
  6],
 [7,
  7,
  14,
  628,
  10,
  13,
  62,
  257,
  955,
  5,
  3,
  164,
  237,
  19,
  20,
  3,
  1762,
  972,
  4,
  1939,
  166,
  3,
  331,
  679,
  37,
  3,
  3422,
  1034,
  637,
  41,
  38,
  20,
  1,
  486,
  1174,
  7,
  7,
  10,
  594,
  955,
  5,
  2,
  2236,
  30,
  1,
  18,
  13,
  865,
  175,
  5,
  665,
  15,
  1,
  4,
  1,
  344,
  666,
  4,
  337,
  2,
  90,
  1197,
  5,
  1260,
  32,
  1652,
  3155,
  20,
  7,
  7,
  34,
  235,
  174,
  10,
  196,
  2621,
  41,
  936,
  1822,
  4,
  250,
  14,
  10,
  608,
  12,
  3751,
  13,
  569,
  14,
  204,
  554,
  24,
  1177,
  10,
  67,
  63,
  132,
  26,
  7,
  7,
  5,
  3380,
  47,
  214,
  1983,
  16,
  11,
  1895,
  7,
  7,
  1,
  265,
  13,
  32,
  393,
  26,
  297,
  9,
  13,
  7,
  7,
  180,
  2368,
  73,
  869,
  51,
  7,
  7,
  23,
  33,
  485,
  3943,
  114,
  589,
  27,
  297,
  5,
  27,
  215,
  392,
  105,
  3198,
  68,
  201,
  2,
  3629,
  18,
  33,
  68,
  443,
  5,
  27,
  7,
  7,
  1,
  546,
  4,
  193,
  5,
  27,
  7,
  7,
  3198,
  13,
  3,
  53,
  79,
  127,
  54,
  26,
  13,
  3,
  53,
  79,
  127,
  35,
  1840,
  4600,
  2,
  40,
  8,
  445,
  21,
  728,
  11,
  1099,
  172,
  5,
  1,
  194,
  8,
  168,
  134,
  8,
  1,
  19,
  7,
  7,
  46,
  13,
  54,
  799,
  1613,
  5,
  374,
  2,
  1343,
  1,
  1103,
  4,
  1,
  56,
  2,
  132,
  3198,
  205,
  25,
  4650,
  1,
  2412,
  2,
  26,
  118,
  2925,
  5,
  131,
  989,
  1,
  1276,
  329,
  3,
  1720,
  37,
  11,
  19,
  5,
  223,
  42,
  1,
  194,
  12,
  825,
  29,
  4,
  1,
  4,
  1,
  3964,
  4278,
  68,
  2150,
  2,
  12,
  11,
  205,
  25,
  24,
  2412,
  20,
  1,
  972,
  2,
  24,
  4,
  1,
  4600,
  15,
  32,
  407,
  4055,
  1505,
  5,
  1819,
  71,
  4,
  1,
  2261,
  960,
  7,
  7,
  18,
  46,
  13,
  22,
  71,
  1819,
  5,
  27,
  222,
  1,
  19,
  1391,
  1147,
  172,
  5,
  139,
  46,
  34,
  73,
  40,
  196,
  29,
  1,
  471,
  73,
  662,
  41,
  568,
  73,
  430,
  89,
  75,
  1,
  1334,
  194,
  12,
  5,
  60,
  45,
  3198,
  2605,
  112,
  3,
  3964,
  1303,
  97,
  12,
  58,
  4,
  260,
  27,
  233,
  96,
  1269,
  16,
  1,
  19,
  5,
  2862,
  2,
  227,
  55,
  37,
  1,
  13,
  53,
  60,
  247,
  7,
  7,
  73,
  117,
  26,
  13,
  3,
  79,
  127,
  189,
  73,
  86,
  117,
  12,
  26,
  13,
  3,
  853,
  190,
  14,
  3,
  1075,
  2,
  8,
  51,
  1703,
  1186,
  26,
  100,
  27,
  2,
  55,
  2453,
  2,
  4,
  260,
  47,
  2412,
  36,
  1072,
  4889,
  2,
  1072,
  2883,
  12,
  106,
  100,
  1107,
  15,
  26,
  13,
  86,
  4,
  1721,
  2519,
  132,
  12,
  4957,
  4741,
  708,
  134,
  13,
  34,
  2481,
  7,
  7,
  26,
  13,
  86,
  37,
  29,
  1,
  204,
  113,
  3,
  2811,
  1337,
  8,
  1711,
  73,
  206,
  85,
  15,
  24,
  3909,
  1643,
  73,
  110,
  75,
  5,
  63,
  84,
  26,
  1283,
  9,
  1440,
  4,
  68,
  22,
  8,
  1,
  228,
  2925,
  5,
  131,
  73,
  86,
  75,
  54,
  2634,
  1613,
  82,
  132,
  26,
  13,
  34,
  3484,
  52,
  31,
  24,
  286,
  2238,
  1711,
  3633,
  2,
  34,
  106,
  403,
  258,
  9,
  34,
  32,
  519,
  2,
  174,
  36,
  1,
  223,
  732,
  919,
  1,
  2150,
  4229,
  11,
  6,
  5,
  4745,
  1819,
  41,
  1,
  972,
  132,
  118,
  26,
  108,
  286,
  34,
  71,
  132,
  118,
  26,
  103,
  9,
  13,
  211,
  3,
  48,
  295,
  451,
  2479,
  2176,
  5,
  1,
  3305,
  132,
  157,
  26,
  476,
  41,
  24,
  35,
  1084,
  38,
  274,
  26,
  118,
  18,
  128,
  2690,
  1,
  348,
  7,
  7,
  11,
  19,
  430,
  157,
  25,
  232,
  4,
  98,
  644,
  5,
  131,
  20,
  11,
  371,
  7,
  7,
  14,
  29,
  96,
  395,
  129,
  495,
  1,
  19,
  6,
  3,
  357,
  458,
  4,
  486,
  3683,
  5,
  1,
  2,
  471,
  38,
  1347,
  2250,
  2614,
  42,
  5,
  1138,
  8,
  15,
  936,
  60,
  29,
  96,
  395,
  6,
  5,
  5,
  1,
  4660,
  1111,
  120,
  21,
  89,
  1785,
  124,
  310,
  32,
  34,
  21,
  40,
  471,
  175,
  64,
  1341,
  1142,
  4521,
  12,
  492,
  211,
  75,
  247,
  15,
  9,
  78,
  46,
  23,
  34,
  106,
  1033,
  8,
  1,
  187,
  7,
  7,
  486,
  6,
  62,
  41,
  243,
  178,
  3683,
  5,
  1,
  508,
  2,
  315,
  84,
  9,
  259,
  1064,
  16,
  126,
  2,
  16,
  420,
  11,
  1895,
  13,
  3,
  80,
  1467,
  421,
  174,
  33,
  1005,
  3031,
  20,
  9,
  2,
  1,
  2374,
  2,
  1031,
  135,
  68,
  1306,
  18,
  584,
  178,
  159,
  30,
  29,
  73,
  157,
  117,
  466,
  2,
  54,
  1819,
  4,
  11,
  453,
  817,
  8,
  402,
  486,
  7,
  7],
 [10,
  554,
  1,
  238,
  4,
  1,
  635,
  170,
  229,
  18,
  876,
  229,
  8,
  10,
  13,
  1,
  751,
  955,
  3223,
  233,
  96,
  106,
  633,
  4,
  1624,
  503,
  1452,
  37,
  654,
  5,
  654,
  175,
  144,
  3823,
  2,
  175,
  1,
  856,
  2,
  14,
  106,
  633,
  4,
  85,
  257,
  2,
  1503,
  524,
  70,
  1,
  1431,
  12,
  1,
  65,
  66,
  2013,
  77,
  1076,
  14,
  3,
  346,
  876,
  1125,
  229,
  2,
  92,
  82,
  3,
  802,
  14,
  3,
  4,
  108,
  183,
  160,
  2,
  314,
  33,
  1016,
  1049,
  1,
  884,
  7,
  7,
  9,
  227,
  25,
  77,
  51,
  418,
  43,
  98,
  4,
  1,
  101,
  66,
  232,
  5,
  131,
  12,
  10,
  1808,
  608,
  297,
  8,
  106,
  74,
  102,
  154,
  38,
  43,
  1,
  282,
  293,
  1,
  28,
  10,
  66,
  268,
  229,
  82,
  1,
  19,
  16,
  32,
  1670,
  4565,
  1202,
  19,
  30,
  230,
  90,
  506,
  13,
  8,
  1,
  200,
  277,
  9,
  293,
  124,
  1397,
  4386,
  337,
  4423,
  1743],
 [11,
  17,
  13,
  34,
  79,
  2,
  34,
  631,
  2,
  34,
  2322,
  10,
  258,
  11,
  17,
  5,
  27,
  28,
  4,
  1,
  88,
  379,
  540,
  1790,
  425,
  1353,
  99,
  12,
  10,
  25,
  123,
  113,
  10,
  36,
  88,
  1353,
  631,
  181,
  99,
  18,
  10,
  58,
  110,
  794,
  11,
  28,
  174,
  9,
  40,
  118,
  22,
  94,
  98,
  287,
  3,
  240,
  12,
  474,
  8,
  1,
  1671,
  64,
  514,
  24,
  316,
  2,
  64,
  575,
  5,
  1260,
  56,
  15,
  91,
  16,
  1,
  2,
  300,
  1,
  17,
  16,
  47,
  281,
  1,
  449,
  2,
  575,
  8,
  1151,
  83,
  22,
  75,
  333,
  69,
  73,
  110,
  853,
  42,
  132,
  391,
  219,
  2465,
  1,
  133,
  4,
  1,
  17,
  18,
  391,
  92,
  29,
  73,
  63,
  6,
  1,
  194,
  12,
  1,
  449,
  45,
  47,
  760,
  4,
  2,
  1,
  575,
  8,
  1151,
  6,
  270,
  4221,
  2,
  2170,
  4,
  3,
  4,
  49,
  76,
  634,
  5,
  2674,
  1587,
  5,
  11,
  147,
  12,
  73,
  25,
  54,
  2600,
  14,
  5,
  49,
  9,
  292,
  36,
  29,
  73,
  63,
  6,
  3,
  1883,
  715,
  24,
  1557,
  2,
  29,
  73,
  850,
  6,
  3,
  631,
  3628,
  4,
  2706,
  2,
  3,
  776,
  2329,
  37,
  943,
  181,
  99,
  92,
  50,
  73,
  428,
  169,
  42,
  49,
  2,
  35,
  9,
  6,
  29,
  10,
  118,
  13,
  413,
  11,
  501,
  490,
  42,
  5,
  27,
  47,
  236,
  4,
  1387,
  912,
  3686,
  37,
  35,
  45,
  684,
  216,
  140,
  5,
  114,
  5,
  2382,
  1,
  449,
  2,
  39,
  240,
  2,
  29,
  1,
  449,
  125,
  6,
  785,
  46,
  8,
  967,
  4,
  1,
  602,
  654,
  15,
  39,
  953,
  20,
  941,
  38,
  137,
  36,
  446,
  172,
  82,
  47,
  236,
  4,
  11,
  17,
  6,
  1070,
  804,
  9,
  44,
  22,
  55,
  279,
  2458],
 [10,
  198,
  1,
  4828,
  20,
  273,
  78,
  10,
  108,
  11,
  65,
  34,
  71,
  11,
  6,
  28,
  4,
  1,
  119,
  817,
  1308,
  20,
  1,
  2627,
  286,
  12,
  10,
  25,
  113,
  12,
  724,
  3,
  65,
  4,
  1770,
  31,
  1,
  286,
  1,
  1393,
  23,
  80,
  1,
  65,
  398,
  23,
  80,
  10,
  108,
  84,
  1,
  65,
  3089,
  186,
  37,
  107,
  5,
  107,
  5,
  385,
  21,
  3882,
  14,
  5,
  812,
  172,
  5,
  634,
  368,
  8,
  64,
  474,
  46,
  6,
  3,
  80,
  3347,
  4,
  48,
  2,
  473,
  47,
  4,
  1,
  101,
  12,
  23,
  473,
  8,
  57,
  652,
  23,
  96,
  48,
  22,
  5,
  104,
  168,
  56,
  137,
  51,
  72,
  1,
  225,
  558,
  10,
  2639,
  1,
  237,
  14,
  43,
  33,
  67,
  850,
  70,
  10,
  108,
  84,
  11,
  4828,
  166,
  70,
  238,
  3168,
  8,
  44,
  434,
  10,
  58,
  189,
  22,
  5,
  104,
  1,
  843,
  17,
  8,
  1,
  273,
  217,
  44,
  3,
  372,
  175,
  1058,
  5,
  1,
  87,
  105,
  99,
  2,
  88,
  4,
  1,
  224,
  101,
  83,
  22,
  982,
  10,
  89,
  623,
  5,
  356,
  84,
  1,
  843,
  17,
  914,
  10,
  2651,
  5,
  414,
  15,
  1,
  2345,
  4,
  1,
  282,
  8,
  1,
  341,
  17,
  9,
  166,
  70,
  645],
 [4585,
  3857,
  4,
  1,
  453,
  7,
  7,
  532,
  31,
  599,
  7,
  7,
  1154,
  1602,
  2121,
  2556,
  2,
  7,
  7,
  115,
  4585,
  39,
  237,
  109,
  2,
  2026,
  5,
  1,
  396,
  1461,
  479,
  5,
  20,
  39,
  366,
  1356,
  5,
  94,
  188,
  3319,
  5,
  863,
  52,
  3,
  109,
  8,
  4404,
  457,
  16,
  39,
  29,
  59,
  209,
  6,
  3,
  944,
  155,
  361,
  3,
  2,
  3,
  1264,
  136,
  8,
  4585,
  513,
  5,
  94,
  290,
  47,
  114,
  82,
  1,
  2197,

In [23]:
X_test

array([[   0,    0,    0, ..., 1050,  746,  162],
       [  12,  159,   58, ...,  397,    7,    7],
       [   0,    0,    0, ...,   51, 1081,   99],
       ...,
       [   0,    0,    0, ...,  124,  198, 3295],
       [   0,    0,    0, ..., 1080,    1, 2473],
       [   0,    0,    0, ...,    1,  341,   28]], dtype=int32)

In [24]:
Y_train = train_data["sentiment"]
Y_test = test_data["sentiment"]

In [25]:
Y_train

39087    0
30893    0
45278    1
16398    0
13653    0
        ..
11284    1
44732    1
38158    0
860      1
15795    1
Name: sentiment, Length: 40000, dtype: int64

#Model building

In [26]:
model = Sequential()
model.add(Embedding(input_dim=5000, output_dim=128, input_length=200))
model.add(LSTM(units=128, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(1, activation='sigmoid'))

In [28]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [29]:
model.compile(optimizer = "adam", loss="binary_crossentropy", metrics=["accuracy"])

In [32]:
model.fit(X_train, Y_train, epochs = 5, batch_size=64, validation_split = 0.2)

Epoch 1/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 215s 415ms/step - accuracy: 0.7259 - loss: 0.5215 - val_accuracy: 0.7200 - val_loss: 0.5413
Epoch 2/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 202s 403ms/step - accuracy: 0.8197 - loss: 0.4065 - val_accuracy: 0.8494 - val_loss: 0.3678
Epoch 3/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 203s 405ms/step - accuracy: 0.8721 - loss: 0.3156 - val_accuracy: 0.8698 - val_loss: 0.3116
Epoch 4/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 201s 402ms/step - accuracy: 0.8972 - loss: 0.2661 - val_accuracy: 0.8679 - val_loss: 0.3190
Epoch 5/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 234s 469ms/step - accuracy: 0.8987 - loss: 0.2553 - val_accuracy: 0.8561 - val_loss: 0.3650

In [34]:
loss, accuracy = model.evaluate(X_test, Y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 37s 116ms/step - accuracy: 0.8554 - loss: 0.3626

In [35]:
print(loss)

0.35852545499801636

In [36]:
print(accuracy)

0.8567000031471252

Building predictive system

In [37]:
def predictive_system(review):
  sequences = tokenizer.texts_to_sequences([review])
  padded_sequences = pad_sequences(sequences, maxlen=200)
  prediction = model.predict(padded_sequences)
  sentiment = "positive" if prediction[0][0] > 0.5 else "negative"
  return sentiment

In [38]:
predictive_system("This movie was fantastic and amazing")

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 580ms/step

'positive'

In [39]:
predictive_system("A trilling adventure with stunning visual")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 312ms/step

'positive'

In [40]:
predictive_system("A visual masterpiece")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step

'positive'

In [45]:
predictive_system("Overall long and slow")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step

'positive'

#Saving Model

In [41]:
model.save("model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [42]:
import joblib
joblib.dump(tokenizer, "tokenizer.pkl")

['tokenizer.pkl']